### PR TITLE
Converts to TypeScript

### PR DESCRIPTION
**Pull request by twokul**
cc @runspired @stefanpenner

### CODE REVIEW

**Comment by stefanpenner** [comment]
nice!

**Comment by hjdivad** [comment]
What do we need to do before we can merge this?

**Comment by twokul** [comment]
After talking to @runspired, we should likely do couple of sanity checks on the size of the final build and benchmarks. He also mentioned we should likely separate out heimdall-tree so we could more accurately see the change in final build size.

thanks,
/alex

**Comment by twokul** [comment]
Build size before:

heimdalljs.cjs.js | heimdalljs.es.js | heimdalljs.iife.js | heimdalljs.umd.js
------------ | -------------  | ------------- | -------------
35647 bytes | 35645 bytes | 35592 bytes | 35808 bytes

Build size after:

heimdalljs.cjs.js | heimdalljs.es.js | heimdalljs.iife.js | heimdalljs.umd.js
------------ | -------------  | ------------- | -------------
33852 bytes | 33850 bytes | 33797 bytes | 34013 bytes

`yarn run trace` before:

➜  heimdalljs-lib git:(master) yarn run trace

  now() ................................... 0 op/s
  Start Stop ..................... 819,318.44 op/s
  Start Stop (with monitor) ....... 59,284.94 op/s
  Increment Monitor ........... 49,935,062.09 op/s

`yarn run trace` after:

➜  heimdalljs-lib git:(typescript) yarn run trace

  now() ................................... 0 op/s
  Start Stop ................... 1,008,584.41 op/s
  Start Stop (with monitor) ...... 183,522.47 op/s
  Increment Monitor ........... 46,972,934.98 op/s

**Comment by twokul** [comment]
@hjdivad @runspired I think this is good to go.

**Comment by hjdivad** [comment]
```
now() ................................... 0 op/s
Start Stop ................... 1,008,584.41 op/s
Start Stop (with monitor) ...... 183,522.47 op/s
Increment Monitor ........... 46,972,934.98 op/s
```

isn't this telling us that the `now` benchmark is simply broken?

**Comment by twokul** [comment]
seems that way

thanks,
/alex

**Pull request merged**
