### PR TITLE
[WIP] Preallocation & Recycling

### PR DESCRIPTION
**Pull request by runspired**
This is a rough first pass the just preheats heimdall by setting up 500 nodes and cookies each.  It also adds `destroy` routines to these classes so that we could reuse the objects should we care to.

Some things that we probably want to do.

- [ ] refactor cookies to tokens
- [ ] push times onto an array and reconstructing node tree from that after completion
- [ ] consider keeping an array of set size (similar to Chrome buffer).  Exceeding the buffer can either make it reuse from the beginning or end collection.
- [ ] session configurable preallocation numbers
  - [ ] consider performing a bulk allocation when exceeding preallocated quantity
    - [ ] track amount of time taken to reallocate for subtraction later when needed

### CODE REVIEW

**Comment by runspired** [comment]
After benchmarking, until we get a setup in which we have a buffer that we reuse from the beginning, this won't make sense.

**Comment by stefanpenner** [comment]
should we keep the branch or remove it?

**Comment by runspired** [comment]
Keep it for a short while, we may come back to it sooner vs. later, but I'd say the max shelf life of this thing is a month, after which anyone finding this note should remove it.

**Comment by stefanpenner** [comment]
> Keep it for a short while, we may come back to it sooner vs. later, but I'd say the max shelf life of this thing is a month, after which anyone finding this note should remove it.
>   Delete branch

sweet

**Pull request closed without merging**
